### ISSUE TITLE
Schema kan inte visas

### ISSUE THREAD

**Issue by SpamixOfficial** [kolplattformen/elev-app.net#32]
Schemat visas inte i appen. Har inte kollat Android men på iOS så är detta ett problem. Ska dock säga att schemavisaren på sidan inte kan visa klasschemat, bara den individuella elevens schema. Detta kan vara anledningen, men är osäker.

**Comment by kajetan-kazimierczak** [comment]
Det ska vara samma schema i appen som den som visas på sidan (den tas därifrån). Sen kanske det är läge att avvakta lite just nu, det brukar alltid strula vid terminstart, innan skolorna är helt klara med schemat och publicerar den ordentligt.

**Comment by SpamixOfficial** [comment]
Ser ut som att schemat nu fungerar på skolplattformen, men tyvärr inte i appen.

**Comment by kajetan-kazimierczak** [comment]
Schemat hos oss verkar fungera som förut. Vi har dock inga valmöjligheter på sajten, ser vara ett schema. Om det inte ser ut så hos dig så kan jag tyvärr inte hjälpa. Alla ser bara sin egen data och hur det ser ut hos dem.

Koden för att komma åt schemat finns här, om du eller någon annan har möjlighet att titta på det. 
https://github.com/kolplattformen/elev-app.net/blob/main/src/Skolplattformen.ElevApp.SkolplattformenApi/ApiTimetable.cs

**Comment by SpamixOfficial** [comment]
Ser ut som att allt fungerar nu! Tack för all hjälp.
