### ISSUE TITLE
Inget schema laddas in

### ISSUE THREAD

**Issue by SpamixOfficial** [kolplattformen/elev-app.net#34]
När jag har loggat in så försöker den ladda in schemat. Detta misslyckas och istället visas ingenting. Samma sak gäller start-och-slut tid, där det bara visas ett streck. 

Är det möjligt att de har bytt tillbaka till sin gamla domän för schemat? 

Bild bifogas
![image](https://github.com/kolplattformen/elev-app.net/assets/99183771/911eaeac-0e06-4c9c-b58e-56c3e509f6d0)

**Comment by kajetan-kazimierczak** [comment]
De verkar ha bytt till någon ny domän. Jag kikar när jag får lite tid.

**Comment by SpamixOfficial** [comment]
> De verkar ha bytt till någon ny domän. Jag kikar när jag får lite tid.

Tack! Ifall jag får tid så tar jag också en titt i eftermiddag

**Comment by kajetan-kazimierczak** [comment]
Det kommer en lösning med nästa release. Troligen innan imorgon.
